version: "3.8"

services:
  nlp-titles:
    container_name: nlp-titles
    build: 
      context: .
      dockerfile: Dockerfile
    image: movies-plot-prediction
    volumes:
      - ./code:/opt/movies/code
      - ./data:/opt/movies/data
      - ./runs:/opt/movies/runs
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "8G"
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
      